default_context:
  _pegasus_version: 2024.6.1
  ai_chat_mode: llm
  ai_image_mode: multiple
  author_name: Charles
  ci: github_actions
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: kamal
  description: It is my app.
  docker_setup: default
  domain_name: localhost:8000
  email: charles.cfw@gmail.com
  enable_github_login: y
  enable_google_login: y
  enable_twitter_login: y
  front_end_framework: react
  include_static_files: y
  marketing_email_platform: mailchimp
  post_process: y
  project_name: My App
  project_slug: my_app
  standalone_front_end: none
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: stripe_hosted
  use_2fa: y
  use_admin_docs: y
  use_api_auth: y
  use_api_keys: y
  use_async_example: y
  use_cloud_media_storage: y
  use_debug_toolbar: y
  use_docker: y
  use_ecommerce_example: y
  use_examples: y
  use_health_checks: y
  use_impersonation: y
  use_sentry: y
  use_subscriptions: y
  use_teams: y
  use_teams_example: y
  use_translations: y
  use_wagtail: y
